# Generated by Django 3.1.3 on 2021-01-10 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('heure', models.TextField()),
                ('details', models.TextField()),
            ],
            options={
                'db_table': 'actualite',
            },
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intial', models.TextField()),
                ('classe', models.IntegerField()),
                ('type_contenue', models.TextField()),
                ('sens_lecture', models.TextField()),
            ],
            options={
                'db_table': 'langue',
            },
        ),
        migrations.CreateModel(
            name='Predication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nom_pred', models.TextField()),
                ('titre', models.TextField()),
                ('sous_titre', models.TextField()),
                ('nom_audio', models.TextField()),
                ('lien_audio', models.TextField()),
                ('duree', models.IntegerField()),
                ('lien_video', models.TextField()),
                ('id_langue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.langue')),
            ],
            options={
                'db_table': 'predication',
            },
        ),
        migrations.CreateModel(
            name='Verset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('contenue', models.TextField()),
                ('id_parab', models.TextField()),
                ('id_langue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.langue')),
                ('id_pred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.predication')),
            ],
            options={
                'db_table': 'verset',
            },
        ),
    ]
