# Generated by Django 3.1.3 on 2021-01-30 16:17

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verset',
            name='contenue',
        ),
        migrations.RemoveField(
            model_name='verset',
            name='id_langue',
        ),
        migrations.RemoveField(
            model_name='verset',
            name='id_parab',
        ),
        migrations.RemoveField(
            model_name='verset',
            name='id_pred',
        ),
        migrations.RemoveField(
            model_name='verset',
            name='numero',
        ),
        migrations.CreateModel(
            name='VersetTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('numero', models.IntegerField()),
                ('contenue', models.TextField()),
                ('id_parab', models.TextField()),
                ('id_pred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.predication')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app.verset')),
            ],
            options={
                'verbose_name': 'verset Translation',
                'db_table': 'verset_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
